services:

  spark-master:
    image: apache/spark:3.5.5

    container_name: financial-risk-spark-master

    hostname: financial-risk-spark-master

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master

    ports:
      - "7077:7077"
      - "8080:8080"

    volumes:
      - ./jobs:/opt/spark/jobs

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    restart: unless-stopped

  spark-worker:
    image: apache/spark:3.5.5

    container_name: financial-risk-spark-worker

    hostname: financial-risk-spark-worker

    depends_on:
      spark-master:
        condition: service_healthy

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://financial-risk-spark-master:7077

    environment:
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_CORES: 1

    volumes:
      - ./jobs:/opt/spark/jobs

    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://financial-risk-spark-master:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    restart: unless-stopped