name: keppler-rabbitmq

services:
  # ==============================================================================
  # BROKER DE MENSAJERÍA (RabbitMQ)
  # ==============================================================================
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: core-broker
    restart: always

    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - TZ=${TZ}
      # - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management path_prefix "${RABBITMQ_BASE_PATH}"

    ports:
      - "5672:5672"   # AMQP (Comunicación Master/Workers)
      - "15672:15672" # Interfaz visual (UI)

    volumes:
      # Persistencia de los mensajes en cola
      - /home/ubuntu/keppler/data/rabbitmq/rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      
    logging:
      options:
        max-size: "10m"
        max-file: "3"
