services:

  spark-worker:
    image: apache/spark:latest

    container_name: financial-risk-spark-worker

    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://financial-risk-spark-master:7077

    networks:
      - financial-risk-network

networks:
  financial-risk-network:
    external: true