name: keppler-spark-master

services:
  # ==============================================================================
  # 1. INIT: Reparación de permisos
  # ==============================================================================
  fix-permissions:
    image: alpine:latest
    user: "0:0"
    container_name: spark-master-init
    volumes:
      - /home/ubuntu/keppler/data/spark:/mnt/spark
    command: >
      sh -c "chown -R 1000:1000 /mnt/spark && chmod -R 775 /mnt/spark"

  # ==============================================================================
  # 2. SERVICIO PRINCIPAL: Spark Master
  # ==============================================================================
  spark-master:
    image: apache/spark:${SPARK_VERSION}
    container_name: core-spark-master
    
    # Corregido: Ahora sí corre verdaderamente como ubuntu (1000) en lugar de root (0)
    user: "1000:0"
    network_mode: host
    
    command: >
      bash -c "pip3 install --no-cache-dir numpy pandas pyarrow && /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    
    environment:
      - TZ=${TZ}
      - HOME=/opt/spark/work
      - SPARK_USER=ubuntu
      - HADOOP_USER_NAME=ubuntu
      - SPARK_DAEMON_JAVA_OPTS=-Duser.name=ubuntu
      - SPARK_MASTER_PORT=${SPARK_MASTER_PORT}
      - SPARK_MASTER_WEBUI_PORT=${SPARK_MASTER_WEBUI_PORT}
      - SPARK_LOCAL_IP=${MY_PRIVATE_IP}

    volumes:
      # Lectura de los pipelines
      - /home/ubuntu/keppler/data-platform/pipelines:/opt/spark/pipelines:ro
      # Persistencia de Spark limpia y alineada con la arquitectura de volúmenes
      - /home/ubuntu/keppler/data/spark/master/data:/opt/spark/work
      - /home/ubuntu/keppler/data/spark/master/logs:/opt/spark/logs

    restart: unless-stopped

    depends_on:
      fix-permissions:
        condition: service_completed_successfully

    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:${SPARK_MASTER_WEBUI_PORT:-8080}')"]
      interval: 20s
      timeout: 10s
      retries: 3
      
    logging:
      options:
        max-size: "10m"
        max-file: "3"
